### PR TITLE
First pass at creating complete server tutorial

### PR DESCRIPTION
**Pull request by njlyon0**
Sorry for doing everything as one huge commit!

### CODE REVIEW

**Comment by angelchen7** [comment]
Thanks for writing this page @njlyon0, it's looking great! 😄  Here are some things I noticed:

- In the "Accessing Data" section on RStudio, we can also download files using the RStudio interface by checking the box(es) next to the file(s) we want, and then clicking ⚙️ **More**, then **Export**. I think it would be handy to include that and rename the section to "Via RStudio (Upload & Download)". 
- In the "Accessing Data" section on sFTP, there's a typo in "Mac uers can use [Cyberduck](https://cyberduck.io/) and Windows users can use [WinSCP](https://winscp.net/eng/index.php)." And also I think we should mention that Cyberduck works perfectly fine for Windows as well. Additionally, in this screenshot, the option is set to FTP instead of sFTP.
image

- In the "Accessing Data" section on the command line, I feel like it's not quite clear how to upload files (I don't know much about this method).

**Comment by brunj7** [comment]
@njlyon0 I think it looks great and that you hit the main points. I pushed a few suggestions in addition to @angelchen7 comments, let me know what you think.

**Comment by njlyon0** [comment]
Okay, I think I've met your feedback @angelchen7, take a look and let me know!

One small tweak, because RStudio, sFTP, and CLI all do download/upload I just removed the "(Upload & Download)" bit from all of the headings (that part was only included to distinguish RStudio from the other two).

**Comment by angelchen7** [comment]
@njlyon0 Good job on your edits! 😄 I don't see anything else but we can keep working on the "Accessing Data Via the Command Line" section a bit more.

**Pull request merged**
